### PR TITLE
player classes draft impl

### PR DESCRIPTION
**Pull request by laper32**
In previous implementations in zombie reloaded/zombie plague/etc, some attributes are only needed for **specific class**.
I mean, some keys just only used for some classes, e.g: key A only used for human, key B only used for zombie, key C only used for something specific.

In ZR/ZP, these keys are mixed together, which is not clear to modify, and not easy for us to expand.
Imo, we should make a key to treat these implementation specific keys individually. In this draft, we call it `attribute`.

This requires us to identify: Which keys are needed for all classes.

Feel free to review or modify it, it just a draft, and further discussion required.

### CODE REVIEW

**Comment by laper32** [comment]
The summary of today's discussion:

To make our development happier, we could let some classes be 'basic class', then inherit these 'basic class'.

This could be looked like with the config structure below:
```
base_class = 
{
    ClassName =  // name
    {
        BaseClass = "" // leave blank if no inheritance.
        health = 100 //
        armor = 0
        gravity = 1.0
        speed = 1.0
        scale = 1.0
        model = ""
        other_basic_config_key = __value
        attributes = { // implementation specific data
        }
        script_logic = ""   // leave blank if no specific implementation
                            // laper32: Should we write an interface then impl it instead of write specific logic file here?
    }
}

player_class = 
{
    my_awesome_player_class = 
    {
        base_class = "__some_base_class" // must fill in data, otherwise will cause fatal error.
        attributes = 
        {
            specific_attribute
        }
    }
}
```
The sample will post at the latest commit.

**Comment by Hichatu** [comment]
Looks good so far

**Comment by Hichatu** [comment]
We should implement it with a simple function, such as

function SetPlayerClass(hPlayer, tPlayerClass)

Where it just parses the class and applies it to the player

**Comment by laper32** [comment]
> We should implement it with a simple function, such as
> 
> `function SetPlayerClass(hPlayer, tPlayerClass)`
> 
> Where it just parses the class and applies it to the player

INDEED, but I need to think how to impl is better.

**Comment by Hichatu** [comment]
I think you can apply human classes within ZombieReborn.lua, perhaps in the SetAllHuman() function since it already loops over all players?

**Comment by laper32** [comment]
> I think you can apply human classes within ZombieReborn.lua, perhaps in the SetAllHuman() function since it already loops over all players?

Yeah, it's in `SetAllHumans()`

> And we should keep the class names consistent, so "first_infection" becomes "Mother Zombie"?

That's fine, I just prefer call 'mother_zombie' as 'first_infection'

**Comment by laper32** [comment]
Let's go!

**Review by Hichatu — APPROVED** [review]

**Review by Darnias — APPROVED** [review]

**Pull request merged**
