### PR TITLE
multilanguage support

### PR DESCRIPTION
**Pull request by MoeMod**
set cvar "zr_language schinese" to switch to other language.

### CODE REVIEW

**Comment by PeakKS** [comment]
It's a good start but I'd like to see use of tokens for translating phrases as opposed to using the english translations as the keys. e.g.
```lua
game_info_translations = {
["en"] = "The game is \x05Humans vs. Zombies\x01, the goal for zombies is to infect all humans by knifing them.",
["scn"] = "当前游戏模式是 \x05僵尸逃跑模式\x01, 僵尸的获胜目标是用刀感染所有人类."
}
...
translations = {
["ZR_GAME_INFO"] = game_info_translations,
...
}

translated_text = tr("ZR_GAME_INFO")
```

**Comment by Hichatu** [comment]
A .cfg for translations would definitely be ideal here, so it is easier for future translators to contribute.

**Comment by xiaooloong** [comment]
这样做翻译有点暴力了，还做做成 i18n 吧。

**Comment by MoeMod** [comment]
close due to some bugs found...

**Comment by MoeMod** [comment]
> It's a good start but I'd like to see use of tokens for translating phrases as opposed to using the english translations as the keys. e.g.
> 
> ```lua
> translations = {
> 	["ZR_GAME_INFO"] = {
> 		["en"] = "The game is \x05Humans vs. Zombies\x01, the goal for zombies is to infect all humans by knifing them.",
> 		["scn"] = "当前游戏模式是 \x05僵尸逃跑模式\x01, 僵尸的获胜目标是用刀感染所有人类."
> 	},
> ...
> }
> 
> translated_text = tr("ZR_GAME_INFO")
> ```

This is a Qt style translate format. No extra work is needed to name every label.

**Comment by Poggicek** [comment]
Yeah but then when someones has to change a translation it's extra work that scales by the amount of supported languages, not great.

**Pull request closed without merging**
